"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Save } from "lucide-react";
import Loader from "@/components/shared/Loader";
import ModuleGuard from "@/components/shared/ModuleGuard";
import api from "@/lib/api/axios";

type Score = { studentProfileId: string; score: number | null; status: "PENDING" | "GRADED" | "EXEMPT" | "MISSING"; feedback?: string | null; studentProfile: { user: { firstName: string; lastName: string } } };
type Evaluation = { id: string; title: string; maxScore: number; status: string; subject: { name: string }; category: { name: string }; scores: Score[] };

export default function EvaluationScoresPage() {
  const { id } = useParams<{ id: string }>();
  const [evaluation, setEvaluation] = useState<Evaluation | null>(null);
  const [scores, setScores] = useState<Score[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setLoading(true); const response = await api.get(`/grades/evaluations/${id}`); const data = response.data.data; setEvaluation(data); setScores(data.scores); } catch (requestError: any) { setError(requestError?.response?.data?.message ?? "No fue posible cargar la evaluación."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { load(); }, [load]);
  const update = (studentProfileId: string, field: "score" | "status" | "feedback", value: string) => setScores((current) => current.map((item) => item.studentProfileId === studentProfileId ? { ...item, [field]: field === "score" ? (value === "" ? null : Number(value)) : value, status: field === "score" && value !== "" ? "GRADED" : item.status } as Score : item));
  async function save() { setSaving(true); setError(null); try { await api.post(`/grades/evaluations/${id}/scores`, { scores: scores.map(({ studentProfileId, score, status, feedback }) => ({ studentProfileId, score, status, feedback: feedback || undefined })) }); await load(); } catch (requestError: any) { setError(requestError?.response?.data?.message ?? "No fue posible guardar las calificaciones."); } finally { setSaving(false); } }
  return <ModuleGuard moduleKey="grades" requireSchoolContext={true}><div className="p-6 lg:p-8 space-y-6">{loading ? <Loader minHeight="300px" /> : !evaluation ? <p className="text-[var(--danger)]">{error ?? "Evaluación no encontrada."}</p> : <><Link href="/grades" className="inline-flex items-center gap-2 text-sm text-[var(--text-secondary)] hover:text-white"><ArrowLeft size={16} />Volver a evaluaciones</Link><div><h1 className="gradient-text text-3xl font-extrabold">{evaluation.title}</h1><p className="text-[var(--text-secondary)]">{evaluation.subject.name} · {evaluation.category.name} · Puntaje máximo: {Number(evaluation.maxScore)}</p></div>{error && <div className="rounded-xl border border-[var(--danger)]/40 bg-[var(--danger)]/10 p-3 text-sm">{error}</div>}<section className="glass-panel rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b border-[var(--border-glass)] text-xs uppercase text-[var(--text-secondary)]"><th className="p-4">Alumno</th><th className="p-4">Puntaje</th><th className="p-4">Estado</th><th className="p-4">Retroalimentación</th></tr></thead><tbody className="divide-y divide-[var(--border-glass)]">{scores.map((item) => <tr key={item.studentProfileId}><td className="p-4 font-medium">{item.studentProfile.user.firstName} {item.studentProfile.user.lastName}</td><td className="p-4"><input disabled={evaluation.status === "CLOSED"} value={item.score ?? ""} onChange={(event) => update(item.studentProfileId, "score", event.target.value)} min="0" max={evaluation.maxScore} step="0.01" type="number" className="glass-input w-24" /></td><td className="p-4"><select disabled={evaluation.status === "CLOSED"} value={item.status} onChange={(event) => update(item.studentProfileId, "status", event.target.value)} className="glass-input"><option value="PENDING">Pendiente</option><option value="GRADED">Calificado</option><option value="EXEMPT">Exento</option><option value="MISSING">No entregó</option></select></td><td className="p-4"><input disabled={evaluation.status === "CLOSED"} value={item.feedback ?? ""} onChange={(event) => update(item.studentProfileId, "feedback", event.target.value)} className="glass-input min-w-48" placeholder="Opcional" /></td></tr>)}</tbody></table></div></section>{evaluation.status !== "CLOSED" && <button disabled={saving} onClick={save} className="glass-button"><Save size={18} />{saving ? "Guardando..." : "Guardar calificaciones"}</button>}</>}</div></ModuleGuard>;
}
